[build]
builder = "NIXPACKS"
buildCommand = "cd Backend && npm run build"
watchPatterns = ["Backend/src/**", "Backend/package.json"]

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd Backend && npm run start:prod"

[env]
NODE_ENV = "production"
PORT = "3000"
